# Generated by Django 2.0.1 on 2018-01-07 22:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_key', models.CharField(max_length=200)),
                ('scoreboard', django.contrib.postgres.fields.jsonb.JSONField()),
                ('luck', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
